# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('caption', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='gala/')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='like.Profile'),
        ),
    ]
